### ISSUE TITLE
Empty segment leads to uncaught C++ exception

### ISSUE THREAD

**Issue by neilmb** [seomoz/url-py#56]
https://github.com/seomoz/url-cpp/blob/503c04b22455951e4c2cff87a0fd7e7a3e119165/src/psl.cpp#L152 throws a C++ exception for hosts that have an empty segment. This exception crashes the python process. I believe it should raise a Python exception that could be handled.

```
$ python -c "import url; print url.parse('//site..com').pld"
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Empty segment in .com
[1]    18020 abort      python -c "import url; print url.parse('//site..com').pld"
```

This has been seen in the wild where it kills a Qless worker process when encountered.

**Comment by b4hand** [comment]
The C++ code appears to be behaving correctly throwing a `std::invalid_argument` exception. Also, I'm not sure why the exception isn't being caught because the [Cython code](https://github.com/seomoz/url-py/blob/2033c71a84f03e7e8d40c567e632afd2e013aad3/url/url.pxd#L75-L76) appears to be correctly declaring a translation to a `ValueError` for the exception.

**Comment by neilmb** [comment]
Is it possible that https://github.com/seomoz/url-py/blob/2033c71a84f03e7e8d40c567e632afd2e013aad3/url/url.pxd#L16-L17 is the winning declaration for those two methods? It looks like we have two definitions of the `PSL` class in `url/url.pxd`!?

**Comment by b4hand** [comment]
Odd, I'll drop that out and see if it fixes anything.
